services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "4443:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wordpress_network
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress_user
      - WORDPRESS_DB_PASSWORD=secure_password
      - WORDPRESS_DB_NAME=wordpress_db
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wordpress_network
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=wordpress_db
      - MYSQL_USER=wordpress_user
      - MYSQL_PASSWORD=secure_password
    volumes:
       - wordpress_db:/var/lib/mysql
    networks:
      - wordpress_network
    restart: unless-stopped

volumes:
  wordpress_files:
  wordpress_db:

networks:
  wordpress_network:
    driver: bridge
