services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    # extra_hosts:
    #   - ${DOMAIN}=${WP_SITE_URL}
    secrets:
      - nginx_ssl_key
      - nginx_ssl_cert
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wordpress_network
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    secrets:
      - db_user_password
      - db_user
      - wp_admin_password
      - wp_user_jack_password
      - wp_salts
    environment:
      # Database Configuration
      - WORDPRESS_DB_HOST=${WP_DB_HOST}
      - WORDPRESS_DB_USER_FILE=/run/secrets/db_user
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_user_password
      - WORDPRESS_DB_NAME=${MD_DATABASE}
      # Site Configuration
      - WORDPRESS_SITE_URL=${WP_SITE_URL}
      - WORDPRESS_SITE_TITLE=${WP_SITE_TITLE}
      - WORDPRESS_SITE_HOST=${WP_SITE_HOST}
      # Admin Configuration
      - WORDPRESS_ADMIN_USER=${WP_ADMIN_USER}
      - WORDPRESS_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WORDPRESS_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      # User Configuration
      - WP_USER1_EMAIL=${WP_USER1_EMAIL}
      - WP_USER1_NAME=${WP_USER1_NAME}
      - WP_USER1_ROLE=${WP_USER1_ROLE}
      - WP_USER1_PASSWORD_FILE=/run/secrets/wp_user_jack_password
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wordpress_network
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    secrets:
      - db_root_password
      - db_user_password
      - db_user
    environment:
      - MD_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MD_WP_PASSWORD_FILE=/run/secrets/db_user_password
      - MD_WP_USER_FILE=/run/secrets/db_user
      - MD_DATABASE=${MD_DATABASE}
    volumes:
       - wordpress_db:/var/lib/mysql
    networks:
      - wordpress_network
    restart: unless-stopped

volumes:
  wordpress_files:
  wordpress_db:

networks:
  wordpress_network:
    driver: bridge

secrets:
  nginx_ssl_key:
    file: ../secrets/ssl/nginx.key
  nginx_ssl_cert:
    file: ../secrets/ssl/nginx.crt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  db_user:
    file: ../secrets/db_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_jack_password:
    file: ../secrets/wp_user_jack_password.txt
  wp_salts:
    file: ../secrets/wp_salts.txt
