services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:alpine
    container_name: nginx
    secrets:
      - nginx_ssl_key
      - nginx_ssl_cert
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wordpress_network
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:alpine
    container_name: wordpress
    secrets:
      - db_user_password
      - db_user
      - wp_admin_password
      - wp_user_jack_password
      - wp_salts
    environment:
      # Database Configuration
      - WORDPRESS_DB_HOST=${WP_DB_HOST}
      - WORDPRESS_DB_USER_FILE=/run/secrets/db_user
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_user_password
      - WORDPRESS_DB_NAME=${MD_DATABASE}
      # Site Configuration
      - WORDPRESS_SITE_URL=${WP_SITE_URL}
      - WORDPRESS_SITE_TITLE=${WP_SITE_TITLE}
      - WORDPRESS_SITE_HOST=${WP_SITE_HOST}
      # Admin Configuration
      - WORDPRESS_ADMIN_USER=${WP_ADMIN_USER}
      - WORDPRESS_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WORDPRESS_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      # User Configuration
      - WP_USER1_EMAIL=${WP_USER1_EMAIL}
      - WP_USER1_NAME=${WP_USER1_NAME}
      - WP_USER1_ROLE=${WP_USER1_ROLE}
      - WP_USER1_PASSWORD_FILE=/run/secrets/wp_user_jack_password
      # Redis
      - WORDPRESS_REDIS_HOST=redis
      - WORDPRESS_REDIS_PORT=6379
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - wordpress_network
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:alpine
    container_name: mariadb
    secrets:
      - db_root_password
      - db_user_password
      - db_user
    environment:
      - MD_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MD_WP_PASSWORD_FILE=/run/secrets/db_user_password
      - MD_WP_USER_FILE=/run/secrets/db_user
      - MD_DATABASE=${MD_DATABASE}
    volumes:
       - wordpress_db:/var/lib/mysql
    networks:
      - wordpress_network
    restart: unless-stopped
      
  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - wordpress_network
    expose:
      - "6379"

  ftp-server:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp-server:alpine
    container_name: ftp_server
    restart: unless-stopped
    environment:
      - FTP_USER=${FTP_USER}
    ports:
      - "21:21"
      - "21100-21110:21100-21110"  # Passive mode ports
    volumes:
      - wordpress_files:/data/wordpress_files  # Bind WordPress files to FTP user home
    secrets:
      - ftp_password
    networks:
      - wordpress_network

  website:
    build:
      context: ./requirements/bonus/website
      dockerfile: Dockerfile
    image: website:alpine
    container_name: website
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - website_files:/app
    networks:
      - wordpress_network

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer:alpine
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - wordpress_network

  cadvisor:
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    image: cadvisor:alpine
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - wordpress_network

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/wordpress_files"
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/wordpress_db"
  website_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/website_files"

networks:
  wordpress_network:
    driver: bridge

secrets:
  nginx_ssl_key:
    file: ../secrets/ssl/nginx.key
  nginx_ssl_cert:
    file: ../secrets/ssl/nginx.crt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  db_user:
    file: ../secrets/db_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_jack_password:
    file: ../secrets/wp_user_jack_password.txt
  wp_salts:
    file: ../secrets/wp_salts.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
