version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./content/index.html:/usr/share/nginx/html/index.html:ro  
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    working_dir: /home/app
